name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bibliontec
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Aguardar MySQL
      run: |
        until mysqladmin ping -h"127.0.0.1" -uroot -proot --silent; do
          echo "Aguardando MySQL iniciar..."
          sleep 2
        done

    - name: Criar tabelas no banco de teste
      run: mysql -h 127.0.0.1 -uroot -proot bibliontec < ./bibliontec.sql
    - name: Dar permissão ao Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Rodar testes
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: bibliontec
      run: npx jest --forceExit --detectOpenHandles


    - name: Empacotar projeto
      run: zip -r BibliONtec.zip .

    - name: Upload do artefato
      uses: actions/upload-artifact@v4
      with:
        name: bibliotec-artifact
        path: BibliONtec.zip 